global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'patroni1'
    static_configs:
      - targets: ['patroni1:8008']
  - job_name: 'patroni2'
    static_configs:
      - targets: ['patroni2:8008']
  - job_name: 'patroni3'
    static_configs:
      - targets: ['patroni3:8008']

